;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Ability.Failed",DevComment="")
+GameplayTagList=(Tag="Data.Montage.Reload",DevComment="")
+GameplayTagList=(Tag="Data.Montage.ShowCrosshair",DevComment="")
+GameplayTagList=(Tag="Data.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Data.ReloadAmmo.Magnitude",DevComment="")
+GameplayTagList=(Tag="Data.ShowCrosshair",DevComment="")
+GameplayTagList=(Tag="Data.StopAbility",DevComment="")
+GameplayTagList=(Tag="Data.StopInterference",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Moon.HoldAndThrow",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Moon.HoldPhotonInGravityField",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Moon.MakeObjectsFloat",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Moon.UseObjectToMoveAcrossMap",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Sun.PhotonShootingMode",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Sun.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Sun.ShootPhoton",DevComment="")
+GameplayTagList=(Tag="State.Sun.PhotonShootingMode",DevComment="")

